# EuroSAT 5-Fold CV

**Week 6 / Task 1**

This notebook runs a stratified **5-fold cross-validation** benchmark on **EuroSAT-MS** and exports:

- `fold metrics CSV`
- `mean±std comparison table`
- `paired t-test p-values`
- `per-class summary table`

The notebook evaluates the local methods already supported in this repo:

- `RGB-CLIP`
- `PCA`
- `NDVI`
- `Tip-Adapter`
- `RS-TransCLIP`
- `Ours`

`DOFA` is exposed through **external CSV templates** because the repo currently does not contain a DOFA model implementation.

In [7]:
import sys
from pathlib import Path

import pandas as pd
import torch

PROJECT_ROOT = Path.cwd().resolve().parent if Path.cwd().name == "notebooks" else Path.cwd().resolve()
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.experiments.eurosat_5fold_cv import (
    DEFAULT_ALL_METHODS,
    run_eurosat_5fold_cv,
)

pd.set_option("display.max_columns", 200)
pd.set_option("display.width", 200)
# NOTE: Do NOT call torch.set_grad_enabled(False) globally here.
# The "Ours" pipeline runs test-time optimization with Adam and needs grads.
# Encoding paths already use inference/no_grad internally where appropriate.

print(f"Project root: {PROJECT_ROOT}")
print(f"PyTorch: {torch.__version__}")

Project root: /Users/tienesng06/Desktop/ACIVS_ThayBach
PyTorch: 2.0.1

## Config

Use `METHODS` and `FOLD_IDS` to control runtime:

- Fast smoke test: `METHODS = ["RGB-CLIP", "PCA"]`, `FOLD_IDS = [0]`
- Even faster smoke test: also set `MAX_TRAIN_PER_CLASS = 24`, `MAX_GALLERY_PER_CLASS = 8`
- `MAX_GALLERY_PER_CLASS` caps both held-out splits: the query fold and the gallery fold
- Full local run: keep the default method list and set `FOLD_IDS = None`
- Add `DOFA`: fill the template CSVs printed below, then set `EXTERNAL_METHOD_INPUTS["DOFA"]`

In [8]:
EUROSAT_ROOT = PROJECT_ROOT / "data" / "EuroSAT_MS.local_backup_20260419"
CLIP_CHECKPOINT = PROJECT_ROOT / "checkpoints" / "ViT-B-16.pt"
RESULTS_DIR = PROJECT_ROOT / "results" / "eurosat_5fold_cv"

METHODS = [
    "RGB-CLIP",
    "PCA",
    "NDVI",
    "Tip-Adapter",
    "RS-TransCLIP",
    "Ours",
    # "DOFA",
]

FOLD_IDS = None
NUM_FOLDS = 5
SEED = 42
BATCH_SIZE = 128
NUM_WORKERS = 0
SHOW_PROGRESS = True
# MAX_GALLERY_PER_CLASS caps both held-out splits: query + gallery.
MAX_TRAIN_PER_CLASS = None
MAX_GALLERY_PER_CLASS = None

EXTERNAL_METHOD_INPUTS = {
    # "DOFA": {
    #     "summary_csv": RESULTS_DIR / "external_templates" / "dofa_fold_metrics_template.csv",
    #     "per_query_csv": RESULTS_DIR / "external_templates" / "dofa_per_query_template.csv",
    # }
}

TIP_ADAPTER_ALPHA = 20.0
TIP_ADAPTER_BETA = 5.5
RS_TRANSCLIP_ALPHA = 0.3

OURS_SIGMA = 0.5
OURS_NUM_STEPS = 5
OURS_LR = 0.01
OURS_LAMBDA_M = 0.1
OURS_K = 5

print(f"EuroSAT root exists: {EUROSAT_ROOT.exists()}")
print(f"CLIP checkpoint exists: {CLIP_CHECKPOINT.exists()}")
print(f"Results dir: {RESULTS_DIR}")
print(f"Methods: {METHODS}")
print(f"Folds: {FOLD_IDS if FOLD_IDS is not None else 'all'}")
print(f"Debug caps: train={MAX_TRAIN_PER_CLASS}, heldout={MAX_GALLERY_PER_CLASS}")

EuroSAT root exists: True
CLIP checkpoint exists: True
Results dir: /Users/tienesng06/Desktop/ACIVS_ThayBach/results/eurosat_5fold_cv
Methods: ['RGB-CLIP', 'PCA', 'NDVI', 'Tip-Adapter', 'RS-TransCLIP', 'Ours']
Folds: all
Debug caps: train=None, heldout=None

## Run 5-Fold CV

This cell writes the main artifacts under `results/eurosat_5fold_cv/`.

In [9]:
result = run_eurosat_5fold_cv(
    root=EUROSAT_ROOT,
    clip_checkpoint=CLIP_CHECKPOINT,
    results_dir=RESULTS_DIR,
    methods=METHODS,
    external_method_inputs=EXTERNAL_METHOD_INPUTS,
    num_folds=NUM_FOLDS,
    fold_ids=FOLD_IDS,
    seed=SEED,
    batch_size=BATCH_SIZE,
    num_workers=NUM_WORKERS,
    show_progress=SHOW_PROGRESS,
    max_train_per_class=MAX_TRAIN_PER_CLASS,
    max_gallery_per_class=MAX_GALLERY_PER_CLASS,
    tip_adapter_alpha=TIP_ADAPTER_ALPHA,
    tip_adapter_beta=TIP_ADAPTER_BETA,
    rs_transclip_alpha=RS_TRANSCLIP_ALPHA,
    ours_sigma=OURS_SIGMA,
    ours_num_steps=OURS_NUM_STEPS,
    ours_lr=OURS_LR,
    ours_lambda_m=OURS_LAMBDA_M,
    ours_k=OURS_K,
)

print(f"Manifest: {result['manifest_path']}")
print("External templates:")
for method, paths in result["external_templates"].items():
    print(f"  {method}:")
    for name, path in paths.items():
        print(f"    {name}: {path}")

Fold 0 RGB+patch query:   0%|          | 0/43 [00:00<?, ?it/s]

Fold 0 RGB+patch gallery:   0%|          | 0/43 [00:00<?, ?it/s]

Encoding test gallery:   0%|          | 0/127 [00:00<?, ?it/s]

Fold 0 PCA fit:   0%|          | 0/127 [00:00<?, ?it/s]

Fold 0 PCA fit (range):   0%|          | 0/127 [00:00<?, ?it/s]

Fold 0 PCA query:   0%|          | 0/43 [00:00<?, ?it/s]

Fold 0 PCA gallery:   0%|          | 0/43 [00:00<?, ?it/s]

Fold 0 NDVI query:   0%|          | 0/43 [00:00<?, ?it/s]

Fold 0 NDVI gallery:   0%|          | 0/43 [00:00<?, ?it/s]

Fold 0 Tip-Adapter query:   0%|          | 0/22 [00:00<?, ?it/s]

Fold 0 Tip-Adapter gallery:   0%|          | 0/22 [00:00<?, ?it/s]

Building gallery patch affinity:   0%|          | 0/22 [00:00<?, ?it/s]

Fold 0 band embeddings query:   0%|          | 0/43 [00:00<?, ?it/s]

Fold 0 band embeddings gallery:   0%|          | 0/43 [00:00<?, ?it/s]

Fold 0 Ours fuse query:   0%|          | 0/5400 [00:00<?, ?it/s]

Fold 0 Ours fuse gallery:   0%|          | 0/5400 [00:00<?, ?it/s]

Fold 1 RGB+patch query:   0%|          | 0/43 [00:00<?, ?it/s]

Fold 1 RGB+patch gallery:   0%|          | 0/43 [00:00<?, ?it/s]

Encoding test gallery:   0%|          | 0/127 [00:00<?, ?it/s]

Fold 1 PCA fit:   0%|          | 0/127 [00:00<?, ?it/s]

Fold 1 PCA fit (range):   0%|          | 0/127 [00:00<?, ?it/s]

Fold 1 PCA query:   0%|          | 0/43 [00:00<?, ?it/s]

Fold 1 PCA gallery:   0%|          | 0/43 [00:00<?, ?it/s]

Fold 1 NDVI query:   0%|          | 0/43 [00:00<?, ?it/s]

Fold 1 NDVI gallery:   0%|          | 0/43 [00:00<?, ?it/s]

Fold 1 Tip-Adapter query:   0%|          | 0/22 [00:00<?, ?it/s]

Fold 1 Tip-Adapter gallery:   0%|          | 0/22 [00:00<?, ?it/s]

Building gallery patch affinity:   0%|          | 0/22 [00:00<?, ?it/s]

Fold 1 band embeddings query:   0%|          | 0/43 [00:00<?, ?it/s]

Fold 1 band embeddings gallery:   0%|          | 0/43 [00:00<?, ?it/s]

Fold 1 Ours fuse query:   0%|          | 0/5400 [00:00<?, ?it/s]

Fold 1 Ours fuse gallery:   0%|          | 0/5400 [00:00<?, ?it/s]

Fold 2 RGB+patch query:   0%|          | 0/43 [00:00<?, ?it/s]

Fold 2 RGB+patch gallery:   0%|          | 0/43 [00:00<?, ?it/s]

Encoding test gallery:   0%|          | 0/127 [00:00<?, ?it/s]

Fold 2 PCA fit:   0%|          | 0/127 [00:00<?, ?it/s]

Fold 2 PCA fit (range):   0%|          | 0/127 [00:00<?, ?it/s]

Fold 2 PCA query:   0%|          | 0/43 [00:00<?, ?it/s]

Fold 2 PCA gallery:   0%|          | 0/43 [00:00<?, ?it/s]

Fold 2 NDVI query:   0%|          | 0/43 [00:00<?, ?it/s]

Fold 2 NDVI gallery:   0%|          | 0/43 [00:00<?, ?it/s]

Fold 2 Tip-Adapter query:   0%|          | 0/22 [00:00<?, ?it/s]

Fold 2 Tip-Adapter gallery:   0%|          | 0/22 [00:00<?, ?it/s]

Building gallery patch affinity:   0%|          | 0/22 [00:00<?, ?it/s]

Fold 2 band embeddings query:   0%|          | 0/43 [00:00<?, ?it/s]

Fold 2 band embeddings gallery:   0%|          | 0/43 [00:00<?, ?it/s]

Fold 2 Ours fuse query:   0%|          | 0/5400 [00:00<?, ?it/s]

Fold 2 Ours fuse gallery:   0%|          | 0/5400 [00:00<?, ?it/s]

Fold 3 RGB+patch query:   0%|          | 0/43 [00:00<?, ?it/s]

Fold 3 RGB+patch gallery:   0%|          | 0/43 [00:00<?, ?it/s]

Encoding test gallery:   0%|          | 0/127 [00:00<?, ?it/s]

Fold 3 PCA fit:   0%|          | 0/127 [00:00<?, ?it/s]

Fold 3 PCA fit (range):   0%|          | 0/127 [00:00<?, ?it/s]

Fold 3 PCA query:   0%|          | 0/43 [00:00<?, ?it/s]

Fold 3 PCA gallery:   0%|          | 0/43 [00:00<?, ?it/s]

Fold 3 NDVI query:   0%|          | 0/43 [00:00<?, ?it/s]

Fold 3 NDVI gallery:   0%|          | 0/43 [00:00<?, ?it/s]

Fold 3 Tip-Adapter query:   0%|          | 0/22 [00:00<?, ?it/s]

Fold 3 Tip-Adapter gallery:   0%|          | 0/22 [00:00<?, ?it/s]

Building gallery patch affinity:   0%|          | 0/22 [00:00<?, ?it/s]

Fold 3 band embeddings query:   0%|          | 0/43 [00:00<?, ?it/s]

Fold 3 band embeddings gallery:   0%|          | 0/43 [00:00<?, ?it/s]

Fold 3 Ours fuse query:   0%|          | 0/5400 [00:00<?, ?it/s]

Fold 3 Ours fuse gallery:   0%|          | 0/5400 [00:00<?, ?it/s]

Fold 4 RGB+patch query:   0%|          | 0/43 [00:00<?, ?it/s]

Fold 4 RGB+patch gallery:   0%|          | 0/43 [00:00<?, ?it/s]

Encoding test gallery:   0%|          | 0/127 [00:00<?, ?it/s]

Fold 4 PCA fit:   0%|          | 0/127 [00:00<?, ?it/s]

Fold 4 PCA fit (range):   0%|          | 0/127 [00:00<?, ?it/s]

Fold 4 PCA query:   0%|          | 0/43 [00:00<?, ?it/s]

Fold 4 PCA gallery:   0%|          | 0/43 [00:00<?, ?it/s]

Fold 4 NDVI query:   0%|          | 0/43 [00:00<?, ?it/s]

Fold 4 NDVI gallery:   0%|          | 0/43 [00:00<?, ?it/s]

Fold 4 Tip-Adapter query:   0%|          | 0/22 [00:00<?, ?it/s]

Fold 4 Tip-Adapter gallery:   0%|          | 0/22 [00:00<?, ?it/s]

Building gallery patch affinity:   0%|          | 0/22 [00:00<?, ?it/s]

Fold 4 band embeddings query:   0%|          | 0/43 [00:00<?, ?it/s]

Fold 4 band embeddings gallery:   0%|          | 0/43 [00:00<?, ?it/s]

Fold 4 Ours fuse query:   0%|          | 0/5400 [00:00<?, ?it/s]

Fold 4 Ours fuse gallery:   0%|          | 0/5400 [00:00<?, ?it/s]

Manifest: /Users/tienesng06/Desktop/ACIVS_ThayBach/results/eurosat_5fold_cv/eurosat_5fold_manifest.json
External templates:
  DOFA:
    summary_csv: /Users/tienesng06/Desktop/ACIVS_ThayBach/results/eurosat_5fold_cv/external_templates/dofa_fold_metrics_template.csv
    per_query_csv: /Users/tienesng06/Desktop/ACIVS_ThayBach/results/eurosat_5fold_cv/external_templates/dofa_per_query_template.csv

## Split Manifest

Each run uses:

- 1 fold as **query**
- the next fold as **gallery**
- the remaining 3 folds as **train/reference**

This keeps query/gallery disjoint and makes the benchmark a real **image-to-image retrieval** protocol.

In [10]:
result["split_manifest_df"]

    fold_id  query_fold_id  gallery_fold_id  class_idx            class_name  train_count  query_count  gallery_count
0         0              0                1          0            AnnualCrop         1800          600            600
1         0              0                1          1                Forest         1800          600            600
2         0              0                1          2  HerbaceousVegetation         1800          600            600
3         0              0                1          3               Highway         1500          500            500
4         0              0                1          4            Industrial         1500          500            500
5         0              0                1          5               Pasture         1200          400            400
6         0              0                1          6         PermanentCrop         1500          500            500
7         0              0                1          7           Residential         1800          600            600
8         0              0                1          8                 River         1500          500            500
9         0              0                1          9               SeaLake         1800          600            600
10        1              1                2          0            AnnualCrop         1800          600            600
11        1              1                2          1                Forest         1800          600            600
12        1              1                2          2  HerbaceousVegetation         1800          600            600
13        1              1                2          3               Highway         1500          500            500
14        1              1                2          4            Industrial         1500          500            500
15        1              1                2          5               Pasture         1200          400            400
16        1              1                2          6         PermanentCrop         1500          500            500
17        1              1                2          7           Residential         1800          600            600
18        1              1                2          8                 River         1500          500            500
19        1              1                2          9               SeaLake         1800          600            600
20        2              2                3          0            AnnualCrop         1800          600            600
21        2              2                3          1                Forest         1800          600            600
22        2              2                3          2  HerbaceousVegetation         1800          600            600
23        2              2                3          3               Highway         1500          500            500
24        2              2                3          4            Industrial         1500          500            500
25        2              2                3          5               Pasture         1200          400            400
26        2              2                3          6         PermanentCrop         1500          500            500
27        2              2                3          7           Residential         1800          600            600
28        2              2                3          8                 River         1500          500            500
29        2              2                3          9               SeaLake         1800          600            600
30        3              3                4          0            AnnualCrop         1800          600            600
31        3              3                4          1                Forest         1800          600            600
32        3              3                4          2  HerbaceousVegetation         1800          600            600
33        3              3                4          3               Highway         1500          500            500
34        3              3                4          4            Industrial         1500          500            500
35        3              3                4          5               Pasture         1200          400            400
36        3              3                4          6         PermanentCrop         1500          500            500
37        3              3                4          7           Residential         1800          600            600
38        3              3                4          8                 River         1500          500            500
39        3              3                4          9               SeaLake         1800          600            600
40        4              4                0          0            AnnualCrop         1800          600            600
41        4              4                0          1                Forest         1800          600            600
42        4              4                0          2  HerbaceousVegetation         1800          600            600
43        4              4                0          3               Highway         1500          500            500
44        4              4                0          4            Industrial         1500          500            500
45        4              4                0          5               Pasture         1200          400            400
46        4              4                0          6         PermanentCrop         1500          500            500
47        4              4                0          7           Residential         1800          600            600
48        4              4                0          8                 River         1500          500            500
49        4              4                0          9               SeaLake         1800          600            600

## Fold Metrics

Raw metrics per fold and per method.

In [11]:
result["fold_metrics_df"]

,method,fold_id,seed,query_fold_id,gallery_fold_id,num_train,num_query,num_gallery,R@1,R@5,R@10,mAP,tip_adapter_alpha,tip_adapter_beta,rs_transclip_alpha,ours_sigma,ours_num_steps,ours_lr,ours_lambda_m,ours_k,avg_query_fusion_ms,avg_query_optimization_ms,avg_gallery_fusion_ms,avg_gallery_optimization_ms
0,RGB-CLIP,0,42,0,1,16200,5400,5400,80.388892,94.629627,97.203702,40.338091,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,RGB-CLIP,1,42,1,2,16200,5400,5400,80.166668,95.722222,97.981483,40.306415,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,RGB-CLIP,2,42,2,3,16200,5400,5400,79.333335,94.537038,97.796297,39.927081,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,RGB-CLIP,3,42,3,4,16200,5400,5400,80.074072,94.759262,97.222221,40.607402,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,RGB-CLIP,4,42,4,0,16200,5400,5400,81.240743,95.074075,97.888887,40.713289,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,PCA,0,42,0,1,16200,5400,5400,83.388889,96.185184,98.037034,42.879319,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,PCA,1,42,1,2,16200,5400,5400,83.796299,96.333331,98.407406,42.732651,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,PCA,2,42,2,3,16200,5400,5400,83.740741,96.351850,98.314816,42.501629,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,PCA,3,42,3,4,16200,5400,5400,83.425927,96.481484,98.388886,42.765113,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,PCA,4,42,4,0,16200,5400,5400,83.759260,95.962965,98.240739,42.839299,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NDVI,0,42,0,1,16200,5400,5400,83.037037,95.962965,97.722220,45.726376,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NDVI,1,42,1,2,16200,5400,5400,83.907408,96.444446,98.222220,45.566857,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NDVI,2,42,2,3,16200,5400,5400,84.074074,96.388888,98.425925,45.236983,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NDVI,3,42,3,4,16200,5400,5400,84.074074,96.240741,98.000002,45.777689,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NDVI,4,42,4,0,16200,5400,5400,83.351851,96.666664,98.574072,45.472861,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Tip-Adapter,0,42,0,1,16200,5400,5400,67.981482,89.462966,94.203705,36.576066,20.0,5.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Tip-Adapter,1,42,1,2,16200,5400,5400,68.000001,89.407408,94.833332,36.527693,20.0,5.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Tip-Adapter,2,42,2,3,16200,5400,5400,68.129629,89.111114,94.574076,36.146144,20.0,5.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Tip-Adapter,3,42,3,4,16200,5400,5400,66.629630,88.555557,94.166666,36.841467,20.0,5.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Tip-Adapter,4,42,4,0,16200,5400,5400,67.592591,89.925927,94.777775,36.813167,20.0,5.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,RS-TransCLIP,0,42,0,1,16200,5400,5400,78.907406,92.462963,95.407408,43.191748,NaN,NaN,0.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,RS-TransCLIP,1,42,1,2,16200,5400,5400,78.796297,92.722225,95.685184,43.069934,NaN,NaN,0.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,RS-TransCLIP,2,42,2,3,16200,5400,5400,77.444446,91.314816,94.888890,42.784371,NaN,NaN,0.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,RS-TransCLIP,3,42,3,4,16200,5400,5400,77.944446,91.759259,94.666666,43.444503,NaN,NaN,0.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,RS-TransCLIP,4,42,4,0,16200,5400,5400,79.777777,92.629629,95.481479,43.578603,NaN,NaN,0.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Ours,0,42,0,1,16200,5400,5400,84.481484,96.296299,98.037034,45.019573,NaN,NaN,NaN,0.5,5.0,0.01,0.1,5.0,1.363405,1.129606,1.389453,1.285250
26,Ours,1,42,1,2,16200,5400,5400,85.685188,96.462965,98.037034,44.866501,NaN,NaN,NaN,0.5,5.0,0.01,0.1,5.0,1.337589,1.105647,1.361525,1.259277
27,Ours,2,42,2,3,16200,5400,5400,85.481483,96.444446,98.500001,44.723925,NaN,NaN,NaN,0.5,5.0,0.01,0.1,5.0,1.297670,1.061428,1.315180,1.217983
28,Ours,3,42,3,4,16200,5400,5400,84.129632,96.166664,98.000002,44.903643,NaN,NaN,NaN,0.5,5.0,0.01,0.1,5.0,1.398281,1.165058,1.391768,1.286201
29,Ours,4,42,4,0,16200,5400,5400,85.333335,96.740741,98.407406,45.494027,NaN,NaN,NaN,0.5,5.0,0.01,0.1,5.0,1.350400,1.108160,1.343773,1.244018

## Mean ± Std Comparison

Primary table for the Week 6 summary.

In [12]:
result["comparison_df"]

         method  num_folds  num_query_mean  num_gallery_mean   R@1_mean   R@1_std R@1_mean_std   R@5_mean   R@5_std R@5_mean_std  R@10_mean  R@10_std R@10_mean_std   mAP_mean   mAP_std mAP_mean_std
0      RGB-CLIP          5          5400.0            5400.0  80.240742  0.685311   80.24±0.69  94.944445  0.479876   94.94±0.48  97.618518  0.376023    97.62±0.38  40.378456  0.306222   40.38±0.31
1           PCA          5          5400.0            5400.0  83.622223  0.197551   83.62±0.20  96.262963  0.197897   96.26±0.20  98.277776  0.149875    98.28±0.15  42.743602  0.147233   42.74±0.15
2          NDVI          5          5400.0            5400.0  83.688889  0.469838   83.69±0.47  96.340741  0.260774   96.34±0.26  98.188888  0.338792    98.19±0.34  45.556153  0.216204   45.56±0.22
3   Tip-Adapter          5          5400.0            5400.0  67.666667  0.613491   67.67±0.61  89.292594  0.504846   89.29±0.50  94.511111  0.313066    94.51±0.31  36.580907  0.280049   36.58±0.28
4  RS-TransCLIP          5          5400.0            5400.0  78.574075  0.905799   78.57±0.91  92.177778  0.612736   92.18±0.61  95.225925  0.428814    95.23±0.43  43.213832  0.313009   43.21±0.31
5          Ours          5          5400.0            5400.0  85.022224  0.677560   85.02±0.68  96.422223  0.214927   96.42±0.21  98.196295  0.237731    98.20±0.24  45.001534  0.294855   45.00±0.29

## Paired t-test

By default this compares every method against `Ours` on the matched fold-level scores.

In [13]:
result["paired_ttest_df"]

   reference_method compared_method metric  n_pairs     t_stat       p_value  significant_p_lt_0_05
0              Ours        RGB-CLIP    R@1        5  10.845875  4.100835e-04                   True
1              Ours        RGB-CLIP   R@10        5   4.098853  1.486698e-02                   True
2              Ours        RGB-CLIP    R@5        5   7.369960  1.806264e-03                   True
3              Ours        RGB-CLIP    mAP        5  50.254795  9.382006e-07                   True
4              Ours             PCA    R@1        5   6.374367  3.106754e-03                   True
5              Ours             PCA   R@10        5  -0.646915  5.529372e-01                  False
6              Ours             PCA    R@5        5   0.908241  4.151227e-01                  False
7              Ours             PCA    mAP        5  22.455108  2.329005e-05                   True
8              Ours            NDVI    R@1        5   3.959277  1.668774e-02                   True
9              Ours            NDVI   R@10        5   0.081214  9.391732e-01                  False
10             Ours            NDVI    R@5        5   1.199310  2.965913e-01                  False
11             Ours            NDVI    mAP        5  -3.581215  2.314256e-02                   True
12             Ours     Tip-Adapter    R@1        5  77.235918  1.684181e-07                   True
13             Ours     Tip-Adapter   R@10        5  28.399564  9.147939e-06                   True
14             Ours     Tip-Adapter    R@5        5  46.722603  1.255215e-06                   True
15             Ours     Tip-Adapter    mAP        5  78.844990  1.550919e-07                   True
16             Ours    RS-TransCLIP    R@1        5  13.828373  1.585170e-04                   True
17             Ours    RS-TransCLIP   R@10        5  13.007545  2.015806e-04                   True
18             Ours    RS-TransCLIP    R@5        5  16.973600  7.064349e-05                   True
19             Ours    RS-TransCLIP    mAP        5  20.710821  3.211013e-05                   True

## Per-Class Table

This table aggregates metrics over the **real query images** of each class across the selected folds.

In [14]:
result["per_class_df"]

,method,query_label,class_name,num_folds,num_queries,mAP_mean,mAP_std,mAP_mean_std,R@1_mean,R@1_std,R@1_mean_std,R@5_mean,R@5_std,R@5_mean_std,R@10_mean,R@10_std,R@10_mean_std
0,RGB-CLIP,0,AnnualCrop,5,3000,40.036042,19.243834,40.04±19.24,83.600000,37.033730,83.60±37.03,96.200000,19.122811,96.20±19.12,98.266667,13.053187,98.27±13.05
1,RGB-CLIP,1,Forest,5,3000,69.750223,23.063212,69.75±23.06,94.566667,22.671205,94.57±22.67,99.100000,9.445620,99.10±9.45,99.466667,7.284681,99.47±7.28
2,RGB-CLIP,2,HerbaceousVegetation,5,3000,44.286981,16.171773,44.29±16.17,89.366667,30.831517,89.37±30.83,98.233333,13.175865,98.23±13.18,99.133333,9.270610,99.13±9.27
3,RGB-CLIP,3,Highway,5,2500,18.982428,6.787924,18.98±6.79,54.920000,49.767302,54.92±49.77,86.120000,34.580687,86.12±34.58,94.240000,23.303210,94.24±23.30
4,RGB-CLIP,4,Industrial,5,2500,51.553678,19.729308,51.55±19.73,88.960000,31.345038,88.96±31.35,97.880000,14.407937,97.88±14.41,98.720000,11.243316,98.72±11.24
5,RGB-CLIP,5,Pasture,5,2000,21.664493,8.016587,21.66±8.02,68.650000,46.403169,68.65±46.40,93.450000,24.746792,93.45±24.75,97.800000,14.672002,97.80±14.67
6,RGB-CLIP,6,PermanentCrop,5,2500,24.278727,9.642573,24.28±9.64,74.320000,43.695553,74.32±43.70,92.360000,26.569019,92.36±26.57,96.040000,19.505655,96.04±19.51
7,RGB-CLIP,7,Residential,5,3000,39.656292,14.092010,39.66±14.09,88.500000,31.907513,88.50±31.91,97.800000,14.670779,97.80±14.67,98.966667,10.114329,98.97±10.11
8,RGB-CLIP,8,River,5,2500,19.672361,5.176467,19.67±5.18,59.120000,49.171056,59.12±49.17,90.640000,29.132969,90.64±29.13,95.880000,19.879227,95.88±19.88
9,RGB-CLIP,9,SeaLake,5,3000,59.827572,27.746895,59.83±27.75,89.266667,30.958817,89.27±30.96,95.033333,21.729157,95.03±21.73,96.800000,17.602934,96.80±17.60
10,PCA,0,AnnualCrop,5,3000,38.436685,14.389486,38.44±14.39,86.100000,34.600420,86.10±34.60,96.366667,18.714940,96.37±18.71,98.066667,13.771666,98.07±13.77
11,PCA,1,Forest,5,3000,67.798083,16.190537,67.80±16.19,95.033333,21.729157,95.03±21.73,99.300000,8.338656,99.30±8.34,99.766667,4.825624,99.77±4.83
12,PCA,2,HerbaceousVegetation,5,3000,39.263416,15.301551,39.26±15.30,84.300000,36.386142,84.30±36.39,97.400000,15.916169,97.40±15.92,98.966667,10.114329,98.97±10.11
13,PCA,3,Highway,5,2500,26.141051,9.745522,26.14±9.75,64.160000,47.962637,64.16±47.96,91.160000,28.393254,91.16±28.39,96.240000,19.026487,96.24±19.03
14,PCA,4,Industrial,5,2500,35.480815,16.522741,35.48±16.52,83.760000,36.889114,83.76±36.89,97.240000,16.385658,97.24±16.39,98.640000,11.584649,98.64±11.58
15,PCA,5,Pasture,5,2000,36.287366,14.323213,36.29±14.32,76.300000,42.534863,76.30±42.53,94.050000,23.661729,94.05±23.66,97.200000,16.501398,97.20±16.50
16,PCA,6,PermanentCrop,5,2500,25.646021,9.354127,25.65±9.35,73.520000,44.131493,73.52±44.13,93.640000,24.408784,93.64±24.41,97.080000,16.840043,97.08±16.84
17,PCA,7,Residential,5,3000,35.835851,16.085846,35.84±16.09,87.833333,32.695492,87.83±32.70,97.133333,16.689570,97.13±16.69,98.733333,11.184987,98.73±11.18
18,PCA,8,River,5,2500,31.294644,12.432846,31.29±12.43,79.280000,40.538117,79.28±40.54,94.720000,22.367873,94.72±22.37,97.320000,16.153079,97.32±16.15
19,PCA,9,SeaLake,5,3000,80.364700,27.612219,80.36±27.61,97.866667,14.451707,97.87±14.45,99.500000,7.054544,99.50±7.05,99.766667,4.825624,99.77±4.83
20,NDVI,0,AnnualCrop,5,3000,45.263174,16.537387,45.26±16.54,87.766667,32.772502,87.77±32.77,96.333333,18.797340,96.33±18.80,97.633333,15.203375,97.63±15.20
21,NDVI,1,Forest,5,3000,73.470253,20.090086,73.47±20.09,93.733333,24.240285,93.73±24.24,98.600000,11.751001,98.60±11.75,99.233333,8.723775,99.23±8.72
22,NDVI,2,HerbaceousVegetation,5,3000,43.339659,14.176271,43.34±14.18,83.500000,37.124243,83.50±37.12,97.633333,15.203375,97.63±15.20,98.700000,11.329289,98.70±11.33
23,NDVI,3,Highway,5,2500,22.794389,6.948306,22.79±6.95,64.480000,47.866962,64.48±47.87,90.960000,28.681134,90.96±28.68,96.160000,19.219838,96.16±19.22
24,NDVI,4,Industrial,5,2500,30.294215,14.359986,30.29±14.36,77.480000,41.779754,77.48±41.78,95.600000,20.513613,95.60±20.51,98.040000,13.864894,98.04±13.86
25,NDVI,5,Pasture,5,2000,40.899347,14.502031,40.90±14.50,76.250000,42.565754,76.25±42.57,94.000000,23.754624,94.00±23.75,96.600000,18.127446,96.60±18.13
26,NDVI,6,PermanentCrop,5,2500,28.405751,9.159814,28.41±9.16,71.440000,45.179009,71.44±45.18,93.400000,24.833177,93.40±24.83,97.200000,16.500573,97.20±16.50
27,NDVI,7,Residential,5,3000,53.875960,15.986117,53.88±15.99,90.966667,28.670651,90.97±28.67,98.666667,11.471679,98.67±11.47,99.500000,7.054544,99.50±7.05
28,NDVI,8,River,5,2500,36.570758,13.840734,36.57±13.84,85.480000,35.237285,85.48±35.24,96.880000,17.389265,96.88±17.39,98.360000,12.703344,98.36±12.70
29,NDVI,9,SeaLake,5,3000,68.402507,27.567519,68.40±27.57,97.333333,16.113414,97.33±16.11,99.133333,9.270610,99.13±9.27,99.433333,7.507619,99.43±7.51
30,Tip-Adapter,0,AnnualCrop,5,3000,36.186220,17.429173,36.19±17.43,77.933333,41.476527,77.93±41.48,94.233333,23.315090,94.23±23.32,96.833333,17.514027,96.83±17.51
31,Tip-Adapter,1,Forest,5,3000,61.121306,24.812740,61.12±24.81,83.366667,37.244166,83.37±37.24,95.300000,21.167413,95.30±21.17,97.800000,14.670779,97.80±14.67
32,Tip-Adapter,2,HerbaceousVegetation,5,3000,31.378299,12.561490,31.38±12.56,78.166667,41.318373,78.17±41.32,93.566667,24.538669,93.57±24.54,96.766667,17.691332,96.77±17.69
33,Tip-Adapter,3,Highway,5,2500,16.368186,4.247577,16.37±4.25,41.480000,49.278605,41.48±49.28,78.840000,40.852441,78.84±40.85,90.400000,29.465018,90.40±29.47
34,Tip-Adapter,4,Industrial,5,2500,54.804584,19.498829,54.80±19.50,83.520000,37.107417,83.52±37.11,96.640000,18.023328,96.64±18.02,98.120000,13.584529,98.12±13.58
35,Tip-Adapter,5,Pasture,5,2000,14.461308,4.408586,14.46±4.41,37.600000,48.450116,37.60±48.45,76.200000,42.596564,76.20±42.60,88.050000,32.445706,88.05±32.45
36,Tip-Adapter,6,PermanentCrop,5,2500,21.331732,7.179384,21.33±7.18,53.400000,49.894246,53.40±49.89,84.880000,35.831539,84.88±35.83,91.360000,28.101001,91.36±28.10
37,Tip-Adapter,7,Residential,5,3000,36.772488,14.098996,36.77±14.10,78.066667,41.386389,78.07±41.39,92.633333,26.127121,92.63±26.13,95.800000,20.062257,95.80±20.06
38,Tip-Adapter,8,River,5,2500,15.700002,3.465603,15.70±3.47,36.880000,48.257612,36.88±48.26,79.760000,40.186918,79.76±40.19,91.000000,28.623901,91.00±28.62
39,Tip-Adapter,9,SeaLake,5,3000,63.958561,27.948242,63.96±27.95,87.000000,33.635950,87.00±33.64,93.666667,24.360214,93.67±24.36,95.633333,20.438643,95.63±20.44
40,RS-TransCLIP,0,AnnualCrop,5,3000,43.203603,22.282647,43.20±22.28,79.633333,40.279106,79.63±40.28,93.033333,25.462685,93.03±25.46,95.800000,20.062257,95.80±20.06
41,RS-TransCLIP,1,Forest,5,3000,73.359247,23.958786,73.36±23.96,93.566667,24.538669,93.57±24.54,97.666667,15.098506,97.67±15.10,98.300000,12.929258,98.30±12.93
42,RS-TransCLIP,2,HerbaceousVegetation,5,3000,49.118402,18.513688,49.12±18.51,89.200000,31.043215,89.20±31.04,97.066667,16.876725,97.07±16.88,98.466667,12.289531,98.47±12.29
43,RS-TransCLIP,3,Highway,5,2500,19.532775,7.368135,19.53±7.37,54.040000,49.846487,54.04±49.85,83.720000,36.925696,83.72±36.93,91.240000,28.276885,91.24±28.28
44,RS-TransCLIP,4,Industrial,5,2500,57.505390,20.823569,57.51±20.82,90.720000,29.021001,90.72±29.02,97.400000,15.916700,97.40±15.92,98.120000,13.584529,98.12±13.58
45,RS-TransCLIP,5,Pasture,5,2000,22.105887,9.565706,22.11±9.57,63.150000,48.251856,63.15±48.25,86.500000,34.180904,86.50±34.18,92.750000,25.937885,92.75±25.94
46,RS-TransCLIP,6,PermanentCrop,5,2500,25.806791,11.268118,25.81±11.27,75.000000,43.309933,75.00±43.31,90.160000,29.791432,90.16±29.79,93.800000,24.120380,93.80±24.12
47,RS-TransCLIP,7,Residential,5,3000,44.986380,16.113825,44.99±16.11,88.633333,31.745889,88.63±31.75,96.366667,18.714940,96.37±18.71,98.033333,13.887519,98.03±13.89
48,RS-TransCLIP,8,River,5,2500,20.441367,6.410344,20.44±6.41,53.920000,49.856071,53.92±49.86,84.720000,35.986659,84.72±35.99,90.920000,28.738197,90.92±28.74
49,RS-TransCLIP,9,SeaLake,5,3000,60.780996,28.313100,60.78±28.31,85.966667,34.739044,85.97±34.74,91.133333,28.430940,91.13±28.43,92.866667,25.742373,92.87±25.74
50,Ours,0,AnnualCrop,5,3000,49.436311,18.702123,49.44±18.70,85.733333,34.979090,85.73±34.98,96.633333,18.039975,96.63±18.04,98.466667,12.289531,98.47±12.29
51,Ours,1,Forest,5,3000,59.818629,14.705770,59.82±14.71,93.933333,23.875767,93.93±23.88,99.433333,7.507619,99.43±7.51,99.833333,4.079759,99.83±4.08
52,Ours,2,HerbaceousVegetation,5,3000,40.149053,12.910553,40.15±12.91,82.700000,37.831033,82.70±37.83,96.766667,17.691332,96.77±17.69,98.700000,11.329289,98.70±11.33
53,Ours,3,Highway,5,2500,21.904387,8.142515,21.90±8.14,65.480000,47.552856,65.48±47.55,91.960000,27.196585,91.96±27.20,96.840000,17.496767,96.84±17.50
54,Ours,4,Industrial,5,2500,55.838768,19.351538,55.84±19.35,91.160000,28.393254,91.16±28.39,98.400000,12.550020,98.40±12.55,98.880000,10.525679,98.88±10.53
55,Ours,5,Pasture,5,2000,26.747783,11.013434,26.75±11.01,77.000000,42.093776,77.00±42.09,92.650000,26.102072,92.65±26.10,95.350000,21.061797,95.35±21.06
56,Ours,6,PermanentCrop,5,2500,24.034524,9.794820,24.03±9.79,73.120000,44.342441,73.12±44.34,91.960000,27.196585,91.96±27.20,95.760000,20.154029,95.76±20.15
57,Ours,7,Residential,5,3000,46.114566,14.910953,46.11±14.91,92.900000,25.686766,92.90±25.69,98.900000,10.431983,98.90±10.43,99.500000,7.054544,99.50±7.05
58,Ours,8,River,5,2500,35.381634,14.763310,35.38±14.76,84.200000,36.481397,84.20±36.48,96.040000,19.505655,96.04±19.51,97.560000,15.431839,97.56±15.43
59,Ours,9,SeaLake,5,3000,77.363963,28.697714,77.36±28.70,96.966667,17.153143,96.97±17.15,99.000000,9.951533,99.00±9.95,99.500000,7.054544,99.50±7.05

## Exported Files

Main CSV outputs:

- `eurosat_5fold_fold_metrics.csv`
- `eurosat_5fold_comparison.csv`
- `eurosat_5fold_paired_ttest.csv`
- `eurosat_5fold_per_class.csv`
- `eurosat_5fold_per_query.csv`
- `eurosat_5fold_split_manifest.csv`

In [15]:
sorted(str(path) for path in RESULTS_DIR.glob("*.csv"))

['/Users/tienesng06/Desktop/ACIVS_ThayBach/results/eurosat_5fold_cv/eurosat_5fold_comparison.csv',
 '/Users/tienesng06/Desktop/ACIVS_ThayBach/results/eurosat_5fold_cv/eurosat_5fold_fold_metrics.csv',
 '/Users/tienesng06/Desktop/ACIVS_ThayBach/results/eurosat_5fold_cv/eurosat_5fold_paired_ttest.csv',
 '/Users/tienesng06/Desktop/ACIVS_ThayBach/results/eurosat_5fold_cv/eurosat_5fold_per_class.csv',
 '/Users/tienesng06/Desktop/ACIVS_ThayBach/results/eurosat_5fold_cv/eurosat_5fold_per_query.csv',
 '/Users/tienesng06/Desktop/ACIVS_ThayBach/results/eurosat_5fold_cv/eurosat_5fold_split_manifest.csv']